#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import hashlib
import shutil
import yaml

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "runtime"
ROUTES = RUNTIME / "packets" / "routes"
PROFILES = RUNTIME / "packets" / "profiles"


def text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def reset_generated(directory: Path) -> None:
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True)


def build_route_packets(runtime: dict, gates: dict) -> dict[str, dict]:
    records: dict[str, dict] = {}
    for runtime_id, runtime_spec in runtime["capabilities"].items():
        manifest_path = ROOT / runtime_spec["manifest"]
        manifest = yaml.safe_load(text(manifest_path))
        capability_id = manifest["id"]
        capability = text(ROOT / manifest["capability"])
        for route_id, route_spec in manifest["routes"].items():
            route_key = f"{capability_id}/{route_id}"
            route_path = ROOT / route_spec["file"]
            output_path = ROUTES / f"{capability_id}--{route_id}.md"
            gate_ids = manifest.get("quality_defaults", [])
            gate_sources=[]; compiled_gates=[]; seen=set()
            for gate_id in gate_ids:
                relative=gates[gate_id]; gate_path=ROOT/relative
                gate_sources.append({"id":gate_id,"path":relative,"sha256":sha256(gate_path)})
                if relative not in seen: compiled_gates.append(f"### {gate_id}\n\nCanonical source: {relative}  \nSHA-256: {sha256(gate_path)}\n\n{text(gate_path)}"); seen.add(relative)
            body = "\n\n".join([
                "<!-- Generated by scripts/build_runtime_packets.py; do not edit. -->",
                f"# Route packet: {route_key}",
                capability,
                text(route_path),
                "## Compiled default gates\n\n" + "\n\n".join(compiled_gates),
                "## Delivery control\n\nReturn substantive work as Draft and show: **Draft · Approve · Revise · Export**",
            ]) + "\n"
            output_path.write_text(body, encoding="utf-8")
            expected = ROOT / runtime_spec["routes"][route_id]
            if expected != output_path:
                raise ValueError(f"Runtime route path mismatch for {route_key}: {expected} != {output_path}")
            records[route_key] = {
                "path": output_path.relative_to(ROOT).as_posix(),
                "bytes": output_path.stat().st_size,
                "source_manifest": manifest_path.relative_to(ROOT).as_posix(),
                "source_route": route_path.relative_to(ROOT).as_posix(), "gate_ids": gate_ids, "gate_sources": gate_sources,
            }
    return records


def build_profile_packets(profile_registry: dict, form_lock: dict, prose_modes: dict) -> dict[str, dict]:
    records: dict[str, dict] = {}
    narrative_defaults = set(form_lock["modes"]["narrative_lock"].get("default_for", []))
    for profile_id, relative in profile_registry.items():
        source_path = ROOT / relative
        profile = yaml.safe_load(text(source_path))
        lock_id = profile.get("default_form_lock")
        if not lock_id:
            lock_id = "narrative_lock" if profile_id in narrative_defaults else "adaptive"
        gate_path = ROOT / profile["quality_gate"]
        output_path = PROFILES / f"{profile_id}.md"
        profile_yaml = yaml.safe_dump(profile, sort_keys=False).strip()
        body = "\n\n".join([
            "<!-- Generated by scripts/build_runtime_packets.py; do not edit. -->",
            f"# Profile packet: {profile_id}",
            f"## Output profile\n\n```yaml\n{profile_yaml}\n```",
            f"## Effective controls\n\nProse mode: `{profile['default_prose_mode']}`  \nForm Lock: `{lock_id}`",
            f"## Final review\n\n{text(gate_path)}",
        ]) + "\n"
        output_path.write_text(body, encoding="utf-8")
        records[profile_id] = {
            "path": output_path.relative_to(ROOT).as_posix(),
            "bytes": output_path.stat().st_size,
            "source_profile": source_path.relative_to(ROOT).as_posix(),
            "form_lock": lock_id,
        }
    return records


def main() -> int:
    reset_generated(ROUTES)
    reset_generated(PROFILES)
    runtime = yaml.safe_load(text(ROOT / "RUNTIME_MANIFEST.yaml"))
    gate_registry = yaml.safe_load(text(ROOT / "config/gates.yaml"))["gates"]
    profile_registry = yaml.safe_load(text(ROOT / "config/output-profiles.yaml"))["registry"]
    form_lock = yaml.safe_load(text(ROOT / "config/form-lock.yaml"))
    prose_modes = yaml.safe_load(text(ROOT / "config/prose-modes.yaml"))["prose_modes"]
    index = {
        "version": runtime["bundle"]["version"],
        "generated": True,
        "routes": build_route_packets(runtime, gate_registry),
        "profiles": build_profile_packets(profile_registry, form_lock, prose_modes),
    }
    index_path = RUNTIME / "packet-index.yaml"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(yaml.safe_dump(index, sort_keys=False), encoding="utf-8")
    print(f"Runtime packets: {len(index['routes'])} routes, {len(index['profiles'])} profiles")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
